[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  | migrations
  | .git
  | .venv
  | venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
known_first_party = ["apps", "config"]