# Generated by Django 4.2.8 on 2025-10-31 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Информационное'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка'), ('SUCCESS', 'Успех')], default='INFO', max_length=20),
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('TELEGRAM', 'Telegram')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('PROCESSING', 'В обработке'), ('SENT', 'Отправлено'), ('FAILED', 'Не удалось')], default='PENDING', max_length=20)),
                ('payload', models.JSONField()),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_messages', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_6badff_idx'), models.Index(fields=['notification', 'method'], name='notificatio_notific_603c90_idx')],
            },
        ),
    ]
