# Generated by Django 5.2.7 on 2025-10-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='outboxmessage',
            name='notificatio_status_6badff_idx',
        ),
        migrations.RemoveIndex(
            model_name='outboxmessage',
            name='notificatio_notific_603c90_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
